# Etapa 1: build
FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: servir contenido estático
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Reemplaza la conf por defecto con la nuestra
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
