services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hypervisor-backend-dev
    image: hypervisor-backend-dev
    volumes:
      - ./:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
      - "8001:8002/udp"
    command: npm run dev
