services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hypervisor-backend-dev
    image: hypervisor-backend-dev
    volumes:
      - ./:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
      - "8001:8001/udp"
      - "8002:8002"
      - "8090:8090"
      - "9229:9229"
    command: npm run dev
